# Generated by Django 4.2.4 on 2023-08-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onvan', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('ax', models.CharField(max_length=25)),
                ('tosif', models.TextField()),
            ],
        ),
    ]
