# Generated by Django 4.2.4 on 2023-08-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='ax',
            field=models.ImageField(upload_to='ax'),
        ),
    ]
