# Generated by Django 4.2.4 on 2023-09-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_shop_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ax', models.ImageField(upload_to='ax')),
                ('noe', models.IntegerField(default=1)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
