# Generated by Django 4.2.4 on 2023-09-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_home_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home',
        ),
    ]
